
package library_management_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Acer
 */
public class ManageBooks extends javax.swing.JFrame {
    
   
    public ManageBooks() {
        
        initComponents();
        
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_bookname = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_authorname = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_bookid = new javax.swing.JTextField();
        delete1 = new javax.swing.JButton();
        combo_semester = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_bookdetails = new rojeru_san.complementos.RSTableMetro();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        searchdata = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/icons8_Moleskine_26px.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 60, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Enter Book Name:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        txt_bookname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_bookname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_booknameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_bookname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 410, 50));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/icons8_Collaborator_Male_26px.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 70, 50));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Author Name:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, -1, -1));

        txt_authorname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_authorname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_authornameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_authorname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 410, 50));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/icons8_Contact_26px.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 50, 50));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/icons8_Unit_26px.png"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, 70, 50));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Semester:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, -1, -1));

        add.setBackground(new java.awt.Color(153, 0, 0));
        add.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 710, 110, 70));

        update.setBackground(new java.awt.Color(153, 0, 0));
        update.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 710, 130, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/icons8_Rewind_48px.png"))); // NOI18N
        jLabel2.setText("Back");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Enter Book ID:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        txt_bookid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_bookid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_bookidFocusLost(evt);
            }
        });
        txt_bookid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bookidActionPerformed(evt);
            }
        });
        jPanel1.add(txt_bookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 410, 50));

        delete1.setBackground(new java.awt.Color(153, 0, 0));
        delete1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        delete1.setForeground(new java.awt.Color(255, 255, 255));
        delete1.setText("DELETE");
        delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete1ActionPerformed(evt);
            }
        });
        jPanel1.add(delete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 710, 110, 70));

        combo_semester.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        combo_semester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semester I", "Semester II", "Semester III", "Semester IV", "Semester V", "Semester VI", "Semester VII", "Semester VIII", " ", " ", " ", " ", " ", " ", " " }));
        jPanel1.add(combo_semester, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 610, 410, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 830));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 50, 30));

        tbl_bookdetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Book Name", "Author", "Semester"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_bookdetails.setColorBackgoundHead(new java.awt.Color(0, 0, 102));
        tbl_bookdetails.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tbl_bookdetails.setColorFilasForeground1(new java.awt.Color(153, 0, 0));
        tbl_bookdetails.setColorFilasForeground2(new java.awt.Color(153, 0, 0));
        tbl_bookdetails.setColorSelBackgound(new java.awt.Color(153, 153, 153));
        tbl_bookdetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tbl_bookdetails.setFuenteFilas(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tbl_bookdetails.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        tbl_bookdetails.setFuenteHead(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        tbl_bookdetails.setRowHeight(40);
        tbl_bookdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_bookdetailsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_bookdetails);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 790, 530));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/icons8_Books_52px_1.png"))); // NOI18N
        jLabel3.setText("Manage Books");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 270, 60));

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 300, 4));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 0, 0));
        jLabel16.setText("Search by book ID:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        searchdata.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchdata.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 0)));
        searchdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchdataActionPerformed(evt);
            }
        });
        jPanel2.add(searchdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 410, 50));

        searchbtn.setBackground(new java.awt.Color(153, 0, 0));
        searchbtn.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        searchbtn.setForeground(new java.awt.Color(255, 255, 255));
        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        jPanel2.add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 110, 50));

        clearbtn.setBackground(new java.awt.Color(153, 0, 0));
        clearbtn.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        clearbtn.setForeground(new java.awt.Color(255, 255, 255));
        clearbtn.setText("Clear");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });
        jPanel2.add(clearbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 90, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 1150, 830));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       System.exit(0);
       
    }//GEN-LAST:event_jLabel1MouseClicked

    private void txt_booknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_booknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_booknameActionPerformed

    private void txt_authornameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_authornameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_authornameActionPerformed

    private void searchdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchdataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchdataActionPerformed

    public void loadData(){
        try{
         Class.forName("com.mysql.cj.jdbc.Driver");
           String url="jdbc:mysql://localhost:3306/library_management_system";
           String user="root";
           String password="";
           Connection con=DriverManager.getConnection(url,user,password);
           Statement st=con.createStatement();
         DefaultTableModel model=new DefaultTableModel(new String[]{"book_id","book_name","author","semester"},0);
         tbl_bookdetails.setModel(model); 
         String sql="SELECT * FROM book_details";
         ResultSet rs=st.executeQuery(sql);
         String bi,bn,a,s;
         while(rs.next()){
          bi=rs.getString("book_id");
          bn=rs.getString("book_name");
          a=rs.getString("author");
          s=rs.getString("semester");
          model.addRow(new Object[]{bi,bn,a,s});
         }
         con.close();
         st.close();
        }
        catch(Exception e)
       {
        System.out.println("error"+e.getMessage());
       }
         
         
    }
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        HomePage home=new HomePage();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void tbl_bookdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_bookdetailsMouseClicked
     
    }//GEN-LAST:event_tbl_bookdetailsMouseClicked

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
                                                             
                                  
   String ID;
    boolean notFound = true;
    
    Connection con = null;
    PreparedStatement pstSelect = null;
    PreparedStatement pstUpdate = null;
    ResultSet rs = null;
    
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        String url = "jdbc:mysql://localhost:3306/library_management_system";
        String user = "root";
        String password = "";
        con = DriverManager.getConnection(url, user, password);
        
        ID = searchdata.getText();
        if ("".equals(ID)) {
            JOptionPane.showMessageDialog(this, "Required Student ID!!");
        } else {
            String sqlSelect = "SELECT * FROM book_details WHERE book_id = ?";
            pstSelect = con.prepareStatement(sqlSelect);
            pstSelect.setString(1, ID);
            rs = pstSelect.executeQuery(); 
            
            if (rs.next()) {
                String bookid = txt_bookid.getText();
                String bookname = txt_bookname.getText();
                String author = txt_authorname.getText();
                String semester = (String) combo_semester.getSelectedItem();
                
                notFound = false;
                String sqlUpdate = "UPDATE book_details SET book_name = ?, author = ?, semester = ? WHERE book_id = ?";
                pstUpdate = con.prepareStatement(sqlUpdate);
                pstUpdate.setString(1, bookname);
                pstUpdate.setString(2, author);
                pstUpdate.setString(3, semester);
                pstUpdate.setString(4, bookid);
                pstUpdate.executeUpdate(); 
                
                loadData();
                JOptionPane.showMessageDialog(this, "Successfully Book Details Updated!!");
            }

            if (notFound) {
                JOptionPane.showMessageDialog(this, "Invalid Book ID!");
            }
        }
    } catch (Exception e) {
        System.out.println("error: " + e.getMessage());
    } finally {
        try {
            if (rs != null) rs.close();
            if (pstSelect != null) pstSelect.close();
            if (pstUpdate != null) pstUpdate.close();
            if (con != null) con.close();
        } catch (Exception e) {
            System.out.println("error: " + e.getMessage());
        }
    }
  
   
    }//GEN-LAST:event_updateActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
      
                                        
      
    String ID;
    boolean found = false;
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        String url = "jdbc:mysql://localhost:3306/library_management_system";
        String user = "root";
        String password = "";

        con = DriverManager.getConnection(url, user, password);

        ID = searchdata.getText();
        if ("".equals(ID)) {
            JOptionPane.showMessageDialog(this, "Book ID required!");
            return;
        }

        String sql = "SELECT * FROM book_details WHERE book_id = ?";
        pst = con.prepareStatement(sql);
        pst.setString(1, ID);
        rs = pst.executeQuery();

        if (rs.next()) {
            txt_bookid.setText(rs.getString("book_id"));
            txt_bookname.setText(rs.getString("book_name"));
            txt_authorname.setText(rs.getString("author"));
            combo_semester.setSelectedItem(rs.getString("semester")); 
            found = true;
        } 

        if (!found) {
            JOptionPane.showMessageDialog(this, "Invalid Book ID!");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Oops", JOptionPane.ERROR_MESSAGE);
    }
    


    }//GEN-LAST:event_searchbtnActionPerformed

    private void txt_bookidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bookidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bookidActionPerformed

    private void delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete1ActionPerformed
                                    
    String ID = searchdata.getText().trim(); // Trim to remove leading/trailing spaces
    if (ID.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Required book ID!");
        return;
    }
    
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        String url = "jdbc:mysql://localhost:3306/library_management_system";
        String user = "root";
        String password = "";
        Connection con = DriverManager.getConnection(url, user, password);

        String sql = "SELECT * FROM book_details WHERE book_id = ?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, ID);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            // Book found, proceed with deletion
            String deleteSql = "DELETE FROM book_details WHERE book_id = ?";
            PreparedStatement deletePst = con.prepareStatement(deleteSql);
            deletePst.setString(1, ID);
            deletePst.executeUpdate(); 

            // Reload data or update UI as needed
            loadData(); // Assuming loadData() updates your UI with refreshed data

            JOptionPane.showMessageDialog(this, "Successfully deleted the book!");
        } else {
            // Book not found
            JOptionPane.showMessageDialog(this, "Invalid book ID!");
        }

        con.close();
        pst.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Oops", JOptionPane.ERROR_MESSAGE);
    }    


    }//GEN-LAST:event_delete1ActionPerformed



public void insertBookDetails() {
    String bookId, bookName, author, semester;
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        String url = "jdbc:mysql://localhost:3306/library_management_system";
        String user = "root";
        String password = "";

        con = DriverManager.getConnection(url, user, password);

        if ("".equals(txt_bookid.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "Book ID required!", "Oops", JOptionPane.ERROR_MESSAGE);
            return;
        } else if ("".equals(txt_bookname.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "Book name required!", "Oops", JOptionPane.ERROR_MESSAGE);
            return;
        } else if ("".equals(txt_authorname.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "Author name required!", "Oops", JOptionPane.ERROR_MESSAGE);
            return;
        } else if ("".equals(combo_semester.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(new JFrame(), "Semester required!", "Oops", JOptionPane.ERROR_MESSAGE);
            return;
        }

        bookId = txt_bookid.getText();
        bookName = txt_bookname.getText();
        author = txt_authorname.getText();
        semester = combo_semester.getSelectedItem().toString();

        // Check if the book already exists
        String queryCheck = "SELECT * FROM book_details WHERE book_id = ?";
        pst = con.prepareStatement(queryCheck);
        pst.setString(1, bookId);
        rs = pst.executeQuery();

        if (rs.next()) {
            JOptionPane.showMessageDialog(new JFrame(), "Book with ID " + bookId + " already exists!", "Oops", JOptionPane.ERROR_MESSAGE);
            return; // Exit method if book already exists
        }

        // Insert the book details
        String query = "INSERT INTO book_details (book_id, book_name, author, semester) VALUES (?, ?, ?, ?)";
        pst = con.prepareStatement(query);
        pst.setString(1, bookId);
        pst.setString(2, bookName);
        pst.setString(3, author);
        pst.setString(4, semester);

        pst.executeUpdate();

        txt_bookid.setText("");
        txt_bookname.setText("");
        txt_authorname.setText("");
        

        JOptionPane.showMessageDialog(null, "Successfully entered book!");
        loadData();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(new JFrame(), "Error: " + e.getMessage(), "Oops", JOptionPane.ERROR_MESSAGE);
    } 
}


    
    
    
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        
         
         
              insertBookDetails(); 
             
             
         
    }//GEN-LAST:event_addActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
                txt_bookid.setText("");
                txt_bookname.setText("");
                txt_authorname.setText("");
                
                searchdata.setText("");
    }//GEN-LAST:event_clearbtnActionPerformed

    private void txt_bookidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_bookidFocusLost
        if(checkDuplicateID()==true){
          JOptionPane.showMessageDialog(null, " Book ID already exist");
      }
    }//GEN-LAST:event_txt_bookidFocusLost
 //if same name enter, unique name required
    public boolean checkDuplicateID()
    {
        String ID=txt_bookid.getText();
        boolean isExist = false;
        try{
         String url = "jdbc:mysql://localhost:3306/library_management_system";
         Class.forName("com.mysql.cj.jdbc.Driver");
         Connection con = DriverManager.getConnection(url, "root" ,"");
         PreparedStatement pst = con.prepareStatement("Select * from book_details where book_id=?");
        
        pst.setString(1,ID);
        
        ResultSet rs=pst.executeQuery();
        if(rs.next()){
            isExist=true;
        }
        else{
            isExist=false;
        }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
        return isExist;
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             ManageBooks  x= new ManageBooks();
             x.loadData();
             x.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton clearbtn;
    private javax.swing.JComboBox<String> combo_semester;
    private javax.swing.JButton delete1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField searchdata;
    private rojeru_san.complementos.RSTableMetro tbl_bookdetails;
    private javax.swing.JTextField txt_authorname;
    private javax.swing.JTextField txt_bookid;
    private javax.swing.JTextField txt_bookname;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
