
package library_management_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Acer
 */
public class ManageStudents extends javax.swing.JFrame {
    
   
    public ManageStudents() {
        
        initComponents();
        
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_studentname = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_studentid = new javax.swing.JTextField();
        delete1 = new javax.swing.JButton();
        combo_semester = new javax.swing.JComboBox<>();
        combo_faculty = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_studentsdetails = new rojeru_san.complementos.RSTableMetro();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        searchdata = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/icons8_Moleskine_26px.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 60, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Enter Student Name:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        txt_studentname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_studentname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_studentnameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_studentname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 410, 50));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/icons8_Collaborator_Male_26px.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 70, 50));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Faculty:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/icons8_Contact_26px.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 50, 50));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/icons8_Unit_26px.png"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, 70, 50));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Semester:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, -1, -1));

        add.setBackground(new java.awt.Color(153, 0, 0));
        add.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 710, 110, 70));

        update.setBackground(new java.awt.Color(153, 0, 0));
        update.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 710, 130, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/icons8_Rewind_48px.png"))); // NOI18N
        jLabel2.setText("Back");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Enter Student ID:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        txt_studentid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_studentid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_studentidFocusLost(evt);
            }
        });
        txt_studentid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_studentidActionPerformed(evt);
            }
        });
        jPanel1.add(txt_studentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 410, 50));

        delete1.setBackground(new java.awt.Color(153, 0, 0));
        delete1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        delete1.setForeground(new java.awt.Color(255, 255, 255));
        delete1.setText("DELETE");
        delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete1ActionPerformed(evt);
            }
        });
        jPanel1.add(delete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 710, 110, 70));

        combo_semester.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        combo_semester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semester I", "Semester II", "Semester III", "Semester IV", "Semester V", "Semester VI", "Semester VII", "Semester VIII", " ", " ", " ", " ", " ", " ", " " }));
        jPanel1.add(combo_semester, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 610, 410, 50));

        combo_faculty.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        combo_faculty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BCA", "CSIT", "BIM", "BHM", " " }));
        combo_faculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_facultyActionPerformed(evt);
            }
        });
        jPanel1.add(combo_faculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 410, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 830));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 50, 30));

        tbl_studentsdetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Name", "Faculty", "Semester"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_studentsdetails.setColorBackgoundHead(new java.awt.Color(0, 0, 102));
        tbl_studentsdetails.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tbl_studentsdetails.setColorFilasForeground1(new java.awt.Color(153, 0, 0));
        tbl_studentsdetails.setColorFilasForeground2(new java.awt.Color(153, 0, 0));
        tbl_studentsdetails.setColorSelBackgound(new java.awt.Color(153, 153, 153));
        tbl_studentsdetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tbl_studentsdetails.setFuenteFilas(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tbl_studentsdetails.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        tbl_studentsdetails.setFuenteHead(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        tbl_studentsdetails.setRowHeight(40);
        tbl_studentsdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_studentsdetailsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_studentsdetails);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 790, 530));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/icons8_Student_Male_100px.png"))); // NOI18N
        jLabel3.setText("Manage Students");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 370, 100));

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 260, 4));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 0, 0));
        jLabel16.setText("Search by Student ID:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        searchdata.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchdata.setText("          ");
        searchdata.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 0)));
        searchdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchdataActionPerformed(evt);
            }
        });
        jPanel2.add(searchdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 410, 50));

        searchbtn.setBackground(new java.awt.Color(153, 0, 0));
        searchbtn.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        searchbtn.setForeground(new java.awt.Color(255, 255, 255));
        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        jPanel2.add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 110, 50));

        clearbtn.setBackground(new java.awt.Color(153, 0, 0));
        clearbtn.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        clearbtn.setForeground(new java.awt.Color(255, 255, 255));
        clearbtn.setText("Clear");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });
        jPanel2.add(clearbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 90, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 1150, 830));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       System.exit(0);
       
    }//GEN-LAST:event_jLabel1MouseClicked

    private void txt_studentnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_studentnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_studentnameActionPerformed

    private void searchdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchdataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchdataActionPerformed

    public void loadData(){
        try{
         Class.forName("com.mysql.cj.jdbc.Driver");
           String url="jdbc:mysql://localhost:3306/library_management_system";
           String user="root";
           String password="";
           Connection con=DriverManager.getConnection(url,user,password);
           Statement st=con.createStatement();
         DefaultTableModel model=new DefaultTableModel(new String[]{"sid","sname","faculty","semester"},0);
         tbl_studentsdetails.setModel(model); 
         String sql="SELECT * FROM student_details";
         ResultSet rs=st.executeQuery(sql);
         String si,sn,f,s;
         while(rs.next()){
          si=rs.getString("sid");
          sn=rs.getString("sname");
          f=rs.getString("faculty");
          s=rs.getString("semester");
          model.addRow(new Object[]{si,sn,f,s});
         }
         con.close();
         st.close();
        }
        catch(Exception e)
       {
        System.out.println("error"+e.getMessage());
       }
         
         
    }
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        HomePage home=new HomePage();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void tbl_studentsdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_studentsdetailsMouseClicked
     
    }//GEN-LAST:event_tbl_studentsdetailsMouseClicked

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
                                    
    String ID;
    boolean notFound = true;
    
    Connection con = null;
    PreparedStatement pstSelect = null;
    PreparedStatement pstUpdate = null;
    ResultSet rs = null;
    
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        String url = "jdbc:mysql://localhost:3306/library_management_system";
        String user = "root";
        String password = "";
        con = DriverManager.getConnection(url, user, password);
        
        ID = searchdata.getText();
        if ("".equals(ID)) {
            JOptionPane.showMessageDialog(this, "Required Student ID!!");
        } else {
            String sqlSelect = "SELECT * FROM student_details WHERE sid = ?";
            pstSelect = con.prepareStatement(sqlSelect);
            pstSelect.setString(1, ID);
            rs = pstSelect.executeQuery(); 
            
            if (rs.next()) {
                String sid = txt_studentid.getText();
                String sname = txt_studentname.getText();
                String faculty = (String) combo_faculty.getSelectedItem();
                String semester = (String) combo_semester.getSelectedItem();
                
                notFound = false;
                String sqlUpdate = "UPDATE student_details SET sname = ?, faculty = ?, semester = ? WHERE sid = ?";
                pstUpdate = con.prepareStatement(sqlUpdate);
                pstUpdate.setString(1, sname);
                pstUpdate.setString(2, faculty);
                pstUpdate.setString(3, semester);
                pstUpdate.setString(4, sid);
                pstUpdate.executeUpdate(); 
                
                loadData();
                JOptionPane.showMessageDialog(this, "Successfully Student Details Updated!!");
            }

            if (notFound) {
                JOptionPane.showMessageDialog(this, "Invalid Student ID!");
            }
        }
    } catch (Exception e) {
        System.out.println("error: " + e.getMessage());
    } finally {
        try {
            if (rs != null) rs.close();
            if (pstSelect != null) pstSelect.close();
            if (pstUpdate != null) pstUpdate.close();
            if (con != null) con.close();
        } catch (Exception e) {
            System.out.println("error: " + e.getMessage());
        }
    }


    }//GEN-LAST:event_updateActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
      
                                        
    String ID;
    boolean notFound = true;
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        String url = "jdbc:mysql://localhost:3306/library_management_system";
        String user = "root";
        String password = "";
        con = DriverManager.getConnection(url, user, password);
        
        ID = searchdata.getText();
        if ("".equals(ID)) {
            JOptionPane.showMessageDialog(this, "Required Student ID!!");
        } else {
            String sql = "SELECT * FROM student_details WHERE sid = ?";
            pst = con.prepareStatement(sql);
            pst.setString(1, ID);
            rs = pst.executeQuery(); 
            
            if (rs.next()) {
                txt_studentid.setText(rs.getString("sid"));
                txt_studentname.setText(rs.getString("sname"));
                combo_faculty.setSelectedItem(rs.getString("faculty"));
                combo_semester.setSelectedItem(rs.getString("semester")); 
                notFound = false;
            }

            if (notFound) {
                JOptionPane.showMessageDialog(this, "Invalid Student ID!!");
            }
        }
    } catch (Exception e) {
        System.out.println("error: " + e.getMessage());
    } finally {
        try {
            if (rs != null) rs.close();
            if (pst != null) pst.close();
            if (con != null) con.close();
        } catch (Exception e) {
            System.out.println("error: " + e.getMessage());
        }
    }

  
    }//GEN-LAST:event_searchbtnActionPerformed

    private void txt_studentidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_studentidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_studentidActionPerformed

    private void delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete1ActionPerformed
     String ID;
       int notFound=0;
       
      try{
           Class.forName("com.mysql.cj.jdbc.Driver");
           String url="jdbc:mysql://localhost:3306/library_management_system";
           String user="root";
           String password="";
           Connection con=DriverManager.getConnection(url,user,password);
           Statement st=con.createStatement();
           
            ID=searchdata.getText();
            if("".equals(ID)){
            JOptionPane.showMessageDialog(this,"Required StudentID!!");
           }
            else{
               String sql="SELECT * FROM student_details WHERE sid="+ID;
               ResultSet rs=st.executeQuery(sql); 
               while(rs.next()){                  
                  notFound=1;
               String sql1="DELETE FROM student_details WHERE sid="+ID;
               st.executeUpdate(sql1); 
               loadData();
               JOptionPane.showMessageDialog(this,"Sucessfully Student detailed Deleted!!");
               
               }
               con.close();
               st.close();
               if(notFound==0){
                   JOptionPane.showMessageDialog(this,"Invalid Student ID!!");
               }
               
            }
           }
       
       catch(Exception e)
       {
        System.out.println("error"+e.getMessage());
       }    
    }//GEN-LAST:event_delete1ActionPerformed

   public void insertstudentdetails() {
    String query = "INSERT INTO student_details(sid, sname, faculty, semester) VALUES (?, ?, ?, ?)";
    String sid, sname, faculty, semester;

    try {
        // Load the MySQL JDBC driver
        Class.forName("com.mysql.cj.jdbc.Driver");

        // Establish connection to the database
        String url = "jdbc:mysql://localhost:3306/library_management_system";
        String user = "root";
        String password = "";
        try (Connection con = DriverManager.getConnection(url, user, password);
             PreparedStatement pst = con.prepareStatement(query)) {

            // Validate input fields
            if ("".equals(txt_studentid.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "StudentId required !!", "Oops", JOptionPane.ERROR_MESSAGE);
                return;
            } else if ("".equals(txt_studentname.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Studentname required !!", "Oops", JOptionPane.ERROR_MESSAGE);
                return;
            } else if ("".equals(combo_faculty.getSelectedItem().toString())) {
                JOptionPane.showMessageDialog(new JFrame(), "Faculty required !!", "Oops", JOptionPane.ERROR_MESSAGE);
                return;
            } else if ("".equals(combo_semester.getSelectedItem().toString())) {
                JOptionPane.showMessageDialog(new JFrame(), "Semester required !!", "Oops", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Get input values
            sid = txt_studentid.getText();
            sname = txt_studentname.getText();
            faculty = (String) combo_faculty.getSelectedItem();
            semester = (String) combo_semester.getSelectedItem();

            // Set parameters for the prepared statement
            pst.setString(1, sid);
            pst.setString(2, sname);
            pst.setString(3, faculty);
            pst.setString(4, semester);

            // Execute the update
            pst.executeUpdate();

            // Clear input fields
            txt_studentid.setText("");
            txt_studentname.setText("");

            // Show success message
            JOptionPane.showMessageDialog(null, "Successfully Student Entered");

            // Load updated data (assuming loadData() is defined elsewhere)
            loadData();
        }
    } catch (Exception e) {
        System.out.println("Error: " + e.getMessage());
        JOptionPane.showMessageDialog(this," STUDENT ID ALREADY EXIT ");
    }
}

    
    
    
    
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
  
              insertstudentdetails();
         
    }//GEN-LAST:event_addActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
                txt_studentid.setText("");
                txt_studentname.setText("");
                
                searchdata.setText("");
    }//GEN-LAST:event_clearbtnActionPerformed

    private void combo_facultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_facultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_facultyActionPerformed

    private void txt_studentidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_studentidFocusLost
        if(checkDuplicateID()==true){
          JOptionPane.showMessageDialog(null, "Student ID already exist");
      }
    }//GEN-LAST:event_txt_studentidFocusLost
 //if same name enter, unique name required
    public boolean checkDuplicateID()
    {
        String ID=txt_studentid.getText();
        boolean isExist = false;
        try{
         String url = "jdbc:mysql://localhost:3306/library_management_system";
         Class.forName("com.mysql.cj.jdbc.Driver");
         Connection con = DriverManager.getConnection(url, "root" ,"");
         PreparedStatement pst = con.prepareStatement("Select * from student_details where sid=?");
        
        pst.setString(1,ID);
        
        ResultSet rs=pst.executeQuery();
        if(rs.next()){
            isExist=true;
        }
        else{
            isExist=false;
        }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
        return isExist;
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             ManageStudents  x= new ManageStudents();
             x.loadData();
             x.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton clearbtn;
    private javax.swing.JComboBox<String> combo_faculty;
    private javax.swing.JComboBox<String> combo_semester;
    private javax.swing.JButton delete1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField searchdata;
    private rojeru_san.complementos.RSTableMetro tbl_studentsdetails;
    private javax.swing.JTextField txt_studentid;
    private javax.swing.JTextField txt_studentname;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
